point_of_contact: postgres-extensions
production: true
distributed: false
modified: true
legal_exception: false
release_branches:
  - main
  - release.*
code_owners_file_present: false
jira_project_issue_type: Bug
jira_area: Bug
