name: build and install action
description: A reusable set of build and install steps for pg_lake
inputs:
  pg_version:
    description: 'PostgreSQL version'
    required: true
  container_os:
    description: 'Container OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Export PGDIR, PATH and PG_REGRESS_DIR
      shell: bash
      run: |
        echo "PGDIR=/home/postgres/pgsql-${{ inputs.pg_version }}" >> $GITHUB_ENV
        echo "PATH=/home/postgres/pgsql-${{ inputs.pg_version }}/bin:$PATH" >> $GITHUB_ENV
        echo "PG_REGRESS_DIR=/home/postgres/pgsql-${{ inputs.pg_version }}/regress" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: cache_pipenv
      name: Cache pipenv
      with:
        path: ~/.local/share/virtualenvs
        key: pipenv-${{ inputs.container_os }}-${{ hashFiles('Pipfile.lock') }}

    - name: Install pipenv dependencies
      if: steps.cache_pipenv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python3.11 -m pipenv install --dev

    - name: Check formatting
      shell: bash
      run: |
        make check-indent

    - name: Check for typos # ;)
      uses: ./.github/actions/check-typos

    - uses: actions/cache@v4
      id: cache_libduckdb
      name: Cache libduckdb
      with:
        key: duckdb_pglake-${{ inputs.container_os }}-${{ hashFiles('duckdb_pglake/src/**', 'duckdb_pglake/Makefile', 'duckdb_pglake/patches/**', 'duckdb_pglake/extension_config.cmake', 'duckdb_pglake/CMakeLists.txt') }}
        path: |
          duckdb_pglake/libduckdb.so

    - uses: actions/cache@v4
      id: cache_polaris
      name: Cache Polaris
      with:
        key: polaris-${{ inputs.container_os }}-${{ hashFiles('test_common/rest_catalog/Makefile') }}
        path: |
          /home/postgres/pgsql-${{ inputs.pg_version }}/bin/polaris-admin.jar
          /home/postgres/pgsql-${{ inputs.pg_version }}/bin/polaris-server.jar

    - name: Compile and install without duckdb_pglake cache
      if: steps.cache_libduckdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        export PGCOMPAT_BUILD_CONFIG=Release

        # Build duckdb_pglake
        make -j 16 && make install

    - name: Build Polaris if not already in the cache
      if: steps.cache_polaris.outputs.cache-hit != 'true'
      shell: bash
      run: |
        make -j16 install-rest_catalog

    - name: Compile and install with duckdb_pglake cache
      if: steps.cache_libduckdb.outputs.cache-hit == 'true'
      shell: bash
      run: |
        make ci-cached -j 16 && make install-ci-cached

    - name: Install the test extensions
      shell: bash
      run: make -C pg_extension_base prepare-check

    - name: Upload postgres-${{ inputs.pg_version }} artifacts for ${{ inputs.container_os }}
      uses: actions/upload-artifact@v4
      with:
        name: postgres-${{ inputs.pg_version }}-${{ inputs.container_os }}-artifacts
        path: /home/postgres/pgsql-${{ inputs.pg_version }}/

    # need to upload once, same for all pg versions
    - name: Upload avro artifacts for ${{ inputs.container_os }}
      if: ${{ inputs.pg_version == 18 }}
      uses: actions/upload-artifact@v4
      with:
        name: avro-${{ inputs.container_os }}-artifacts
        path: ./avro/lang/c/build/avrolib
