name: build-and-push image action
description: A reusable set of build and push image steps for pg_lake
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  org_name:
    description: 'organization name'
    required: true
  base_image_name:
    description: 'base image name'
    required: true
  base_image_tag:
    description: 'base image tag'
    required: true
  final_image_name:
    description: 'final image name'
    required: true

outputs:
  tag:
    description: 'The tag of the built image'
    value: ${{ steps.push-image.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Build Docker image
      shell: bash
      working-directory: ./docker
      run: |
        GHCR_TOKEN=$(echo ${{ inputs.github_token }} | base64)
        
        TAG=${{ hashFiles('docker/Dockerfile') }}-${{ inputs.base_image_name }}
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${GHCR_TOKEN}" https://ghcr.io/v2/${{ inputs.org_name }}/${{ inputs.final_image_name }}/manifests/$TAG)

        if [ "${HTTP_CODE}" != "200" ]; then
          docker build --target dev_base --build-arg BASE_IMAGE_OS=${{ inputs.base_image_name }} --build-arg BASE_IMAGE_TAG=${{ inputs.base_image_tag }} -t ghcr.io/${{ inputs.org_name }}/${{ inputs.final_image_name }}:$TAG .
          touch rebuild
        fi

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Push Docker image
      id: push-image
      shell: bash
      working-directory: ./docker
      run: |
        TAG=${{ hashFiles('docker/Dockerfile') }}-${{ inputs.base_image_name }}

        if [ -f rebuild ]; then
          docker push ghcr.io/${{ inputs.org_name }}/${{ inputs.final_image_name }}:$TAG
        fi

        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
